all: 1printf 2constants 3scanf 3string 4argv

1printf: 1printf.c
	gcc -o 1printf 1printf.c

2constants: 2constants.c
	gcc -o 2constants 2constants.c

3scanf: 3scanf.c
	gcc -o 3scanf 3scanf.c

3string: 3string.c
	gcc -o 3string 3string.c

4argv: 4argv.c
	gcc -o 4argv 4argv.c

clean:
	rm -f 1printf 2constants 3scanf 3string 4argv
